### ISSUE TITLE
Passing data from Tempate to Module

### ISSUE THREAD

**Issue by fuzzlebuck** [rniemeyer/knockout-amd-helpers#30]
Thanks for this great helper lib, it's awesome!

Is there a way to pass data from the tempate to the initializer of the module?

for example:

cars.html

`<div data-bind="template: {name: 'car', brand: 'mazda'"></div>`
`<div data-bind="template: {name: 'car', brand: 'honda'"></div>`

--

car.template.html

`<div data-bind="module: { name: 'car' }"> `
    `*display stuff about a car*`
`</div>`

--

car.js
```javascript
define(['knockout'], function(ko) {

    var module = {};

    module.initialize = function(brand) {
        *setup the module for a particular car brand*
    };

    return module;
});

**Comment by rniemeyer** [comment]
@fuzzlebuck - It is possible to pass data into the template binding. That data becomes what is bound against the template.

So, it is possible to do something like:

```html
<div data-bind="template: {name: 'car', data: { brand: 'mazda' } }"></div>
```
Then
```html
<div data-bind="module: { name: 'car', data: brand }"></div>
```

Although in your case, it seems like you would want to cut out the intermediate template and use a module directly like:

```html
<div data-bind="module: {name: 'car', data: 'mazda' }"></div>
<div data-bind="module: {name: 'car', data: 'honda' }"></div>
```
This would render the `car` template with the `car` module and pass the data to the `initialize` method (or constructor function, if the module returned a function).

Let me know if you still have any issues.

**Comment by fuzzlebuck** [comment]
That's exactly what I was trying to do! Awesome, thank you :-)
