### ISSUE TITLE
template binding with 'with' doesn't work

### ISSUE THREAD

**Issue by tugberkugurlu** [rniemeyer/knockout-amd-helpers#32]
I am trying to see if template binding works with `with` but it seems not: https://github.com/tugberkugurlu/frameworkless-spa/blob/8e6b2b53005bcff670ffa1c4dd174f5a1216418b/index.html#L16

Am I doing something wrong or is this simply not possible?

> great bindings BTW, thx for sharing them!

**Comment by rniemeyer** [comment]
@tugberkugurlu - you would use the `data` property rather than `with` when using the `template` binding. 

So, like: `template: { name: 'home', data: user }`

**Comment by tugberkugurlu** [comment]
Ah, great! it works, thx! :smile: 

`with` seems more natural to me though. Why didn't want to have it instead of `data`? Any particular reason?

**Comment by rniemeyer** [comment]
@tugberkugurlu - The `template` binding in KO came before the `with` binding and always used `data` as its param to control the value. When the `with` binding was introduced it made more sense called "with" than something like "data" as its own binding name. Hope that makes sense!

**Comment by tugberkugurlu** [comment]
yes, it does! thx.
