### ISSUE TITLE
beforeRemove callback is not firing for template binding

### ISSUE THREAD

**Issue by tugberkugurlu** [rniemeyer/knockout-amd-helpers#33]
I am probably doing something wrong but I cannot get `beforeRemove` event to be fired for template binding [here](https://github.com/tugberkugurlu/frameworkless-spa/blob/6286c65de71e7c2ded45484eeb87106fa0893a7b/index.html#L11) just like [here](http://knockoutjs.com/examples/animatedTransitions.html). I was expecting [this function](https://github.com/tugberkugurlu/frameworkless-spa/blob/6286c65de71e7c2ded45484eeb87106fa0893a7b/app/core/app.js#L6-L12) to be fired on [this call](https://github.com/tugberkugurlu/frameworkless-spa/blob/6286c65de71e7c2ded45484eeb87106fa0893a7b/app/main.js#L23).

Any idea?

**Comment by rniemeyer** [comment]
@tugberkugurlu - the `beforeRemove` (and `afterAdd`) callbacks only apply when being used with the `foreach` option.

**Comment by tugberkugurlu** [comment]
It seems to be the case that only [`afterRender`](http://knockoutjs.com/documentation/template-binding.html#note-4-using-afterrender-afteradd-and-beforeremove) is being fired.

**Comment by tugberkugurlu** [comment]
@rniemeyer yeah, I kind of grasped that after seeing the afterRender working :s what would be the best callback for me to hook into to run an animation while changing the modules (based on my sample)?

**Comment by rniemeyer** [comment]
@tugberkugurlu I haven't looked at that type of interaction in a bit, but here is a custom binding that wraps the template binding that could be customized to do what you want: http://stackoverflow.com/questions/21310666/dynamic-knockout-template-with-transition/21313530#21313530

**Comment by tugberkugurlu** [comment]
@rniemeyer thx, will look at it!
