### ISSUE TITLE
Knockout-amd-helpers does not play well with r.js namespacing

### ISSUE THREAD

**Issue by Domitnator** [rniemeyer/knockout-amd-helpers#36]
Hi Guys,

I just ran into an issue where i use namespacing in my r.js setup (http://requirejs.org/docs/faq-advanced.html#rename). Chrome is giving me the exception:

> app.js:2811 Uncaught TypeError: Unable to process binding "template: function (){return { name:"CatalogRequestSingle"} }"(…)

In version 0.7.4 require is taken from the window object. So i changed the code so that require is actually a dependency:

`define(["knockout", 'require'], function (ko, require){`

And now it works!

Is there a better way to do this? Or is my change just fine?

**Comment by rniemeyer** [comment]
@Domitnator I think that your change is a good one. Feel free to submit a PR, if you would like. Thanks!

**Comment by Domitnator** [comment]
@rniemeyer I will try to submit a PR within 2 weeks (kinda busy right now)!

**Comment by rniemeyer** [comment]
Fixed
