### ISSUE TITLE
Dynamically assigning a template path in renderTemplate()

### ISSUE THREAD

**Issue by lockmotiv** [rniemeyer/knockout-amd-helpers#38]
I wonder if there is a way to do something like this:
`ko.renderTemplate(
						        'tplName',
						        myViewModel,
						        {
						        	path: '/app/templates/custom/XYZ'
						        },
						        this,
						        "replaceNode"
						    );`
I mean, if there is a way to re-write ko.amdTemplateEngine.defaultPath on the fly?

**Comment by lockmotiv** [comment]
Ok. I Got it: 
Just use the path in the name (first argument):
`ko.renderTemplate( '/app/templates/custom/XYZtplName', myViewModel, {}, this, "replaceNode" );`
It's important to define: `ko.amdTemplateEngine.defaultPath = "";`, as they will be concatenated

**Comment by rniemeyer** [comment]
👍
